# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hellostreamingworld.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19hellostreamingworld.proto\x12\x13hellostreamingworld\"3\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\rnum_greetings\x18\x02 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"(\n\nSumRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\"\x1d\n\x0bSumResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\xae\x01\n\x0cMultiGreeter\x12R\n\x08sayHello\x12!.hellostreamingworld.HelloRequest\x1a\x1f.hellostreamingworld.HelloReply\"\x00\x30\x01\x12J\n\x03sum\x12\x1f.hellostreamingworld.SumRequest\x1a .hellostreamingworld.SumResponse\"\x00\x42\x0f\n\x07\x65x.grpc\xa2\x02\x03HSWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hellostreamingworld_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\007ex.grpc\242\002\003HSW'
  _globals['_HELLOREQUEST']._serialized_start=50
  _globals['_HELLOREQUEST']._serialized_end=101
  _globals['_HELLOREPLY']._serialized_start=103
  _globals['_HELLOREPLY']._serialized_end=132
  _globals['_SUMREQUEST']._serialized_start=134
  _globals['_SUMREQUEST']._serialized_end=174
  _globals['_SUMRESPONSE']._serialized_start=176
  _globals['_SUMRESPONSE']._serialized_end=205
  _globals['_MULTIGREETER']._serialized_start=208
  _globals['_MULTIGREETER']._serialized_end=382
# @@protoc_insertion_point(module_scope)
